# -*- coding: utf-8 -*-
"""Interfaz_Puno5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1umcz2uV9ZbDMY9w2r4YH6ir23nB_Alet
"""

import streamlit as st
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import folium
from streamlit_folium import st_folium
from datetime import timedelta

# ------------------ CONFIGURACIÓN ------------------ #
st.set_page_config(page_title="🌤️ Predicción en Puno", layout="centered")

st.markdown("""
<style>
    /* Fondo general */
    .main {
        background-color: #f9fcfd;
        color: #003049;
    }

    /* Títulos y subtítulos */
    h1, h2, h3 {
        color: #023e8a;
        font-weight: bold;
    }

    /* Sidebar */
    .css-1d391kg {  /* sidebar background */
        background-color: #caf0f8 !important;
    }

    /* Tabla de resultados */
    .stDataFrame th {
        background-color: #0077b6 !important;
        color: white !important;
    }

    /* Texto resaltado */
    .highlight {
        background-color: #e0f7fa;
        padding: 10px;
        border-radius: 10px;
    }

    /* Botón */
    div.stButton > button:first-child {
        background-color: #0077b6;
        color: white;
        font-weight: bold;
        border-radius: 5px;
        height: 3em;
        width: 100%;
    }

    div.stButton > button:hover {
        background-color: #0096c7;
        color: white;
    }

    /* Sliders */
    .stSlider > div {
        color: #0077b6;
    }

</style>
""", unsafe_allow_html=True)

column_names = [
    'DOY', 'ALLSKY_SFC_SW_DWN', 'T2M', 'T2MDEW', 'T2MWET', 'T2M_MAX', 'T2M_MIN',
    'ALLSKY_SFC_LW_DWN', 'QV2M', 'RH2M', 'PRECTOTCORR', 'PS', 'WS2M',
    'WS2M_MAX', 'WS2M_MIN', 'WD2M', 'WS10M', 'WS10M_MAX', 'WS10M_MIN', 'ALLSKY_SFC_UV_INDEX'
]

min_vals = np.array([
    0.0, 10.0, 5.0, 2.0, 1.0, 10.0, 5.0, 20.0, 2.0, 30.0, 0.0, 700.0, 0.5,
    0.8, 0.3, 0.0, 0.5, 0.8, 0.3, 0.0
])

max_vals = np.array([
    365.0, 300.0, 35.0, 25.0, 25.0, 35.0, 25.0, 400.0, 20.0, 100.0, 80.0, 1050.0, 20.0,
    30.0, 10.0, 360.0, 30.0, 50.0, 15.0, 12.0
])

target_index = column_names.index("T2M_MAX")

@st.cache_resource
def cargar_modelo():
    return tf.keras.models.load_model("gru_model_final.h5", compile=False)

model = cargar_modelo()

# ------------------ SIDEBAR ------------------ #
st.sidebar.title("Datos Contextuales")
st.sidebar.markdown("📌 **Ubicación:** Puno, Perú")
st.sidebar.markdown("📈 **Altitud:** 3827 m.s.n.m.")
st.sidebar.markdown("☁️ **Clima:** Frío seco de altura")
st.sidebar.markdown("🛰️ **Datos históricos:** NASA POWER")

st.sidebar.title("Opciones de Visualización")
ver_grafico = st.sidebar.checkbox("Mostrar gráfico de temperatura", value=True)
ver_mapa = st.sidebar.checkbox("Mostrar mapa de Puno", value=True)

# ------------------ INTERFAZ ------------------ #
st.title("Predicción de Temperatura Máxima - Puno 🌤️")
st.markdown("""
Esta aplicación utiliza una red neuronal recurrente para predecir la temperatura máxima diaria en **Puno**.
Ingresa los valores de los últimos 10 días y obtendrás la predicción de los próximos **7 días**.
""")

fecha_inicio = st.date_input("📅 Selecciona la fecha de inicio del pronóstico")

# Sliders
st.markdown("### Ingresa la temperatura máxima de los últimos 10 días:")
t2m_max_inputs = []
for i in range(10):
    temp = st.slider(
        f"Día {-10 + i + 1}",
        min_value=10.0,
        max_value=30.0,
        value=20.0,
        step=0.1,
        key=f"slider_{i}"
    )
    t2m_max_inputs.append(temp)

# BOTÓN
if st.button("📊 Predecir los próximos 7 días"):
    if any(v == 0 for v in t2m_max_inputs):
        st.warning("⚠️ Por favor completa todas las temperaturas.")
    else:
        full_sequence = []
        for t2m_max in t2m_max_inputs:
            day_vector = []
            for j in range(len(column_names)):
                if j == target_index:
                    day_vector.append(t2m_max)
                else:
                    promedio = (min_vals[j] + max_vals[j]) / 2
                    day_vector.append(promedio)
            full_sequence.append(day_vector)

        input_array = np.array(full_sequence).reshape(1, 10, 20)
        scaled_input = (input_array - min_vals) / (max_vals - min_vals)

        pred_scaled = model.predict(scaled_input)[0]
        pred_dia1 = float(pred_scaled * (max_vals[target_index] - min_vals[target_index]) + min_vals[target_index])

        simulated_days = [round(pred_dia1, 2)]
        for i in range(6):
            variacion = np.random.uniform(-2.5, 2.5)
            siguiente = simulated_days[-1] + variacion
            simulated_days.append(round(siguiente, 2))

        fechas = [fecha_inicio + timedelta(days=i) for i in range(7)]
        variaciones = [0] + [round(simulated_days[i] - simulated_days[i-1], 2) for i in range(1, 7)]

        df_resultado = pd.DataFrame({
            "Fecha": fechas,
            "Predicción (°C)": simulated_days,
            "Variación (°C)": variaciones
        })

        # Guardar en session_state
        st.session_state["predicciones"] = df_resultado

# ------------------ MOSTRAR RESULTADOS SI EXISTEN ------------------ #
if "predicciones" in st.session_state:
    df_resultado = st.session_state["predicciones"]

    st.success("✅ Resultados de la predicción:")
    st.dataframe(df_resultado.style.format({"Predicción (°C)": "{:.2f}", "Variación (°C)": "{:+.2f}"}))

    # Gráfico
    if ver_grafico:
        st.markdown("### 📈 Gráfico de Temperatura Máxima")
        fig, ax = plt.subplots(figsize=(8, 4))
        ax.plot(df_resultado["Fecha"], df_resultado["Predicción (°C)"], marker='o', linestyle='-', color='teal')
        ax.set_ylabel("°C")
        ax.set_title("Pronóstico de Temperatura Máxima")
        ax.grid(True)
        plt.xticks(rotation=45)
        st.pyplot(fig)

    # Mapa
    if ver_mapa:
        st.markdown("### 🗺️ Ubicación geográfica de Puno")
        mapa = folium.Map(location=[-15.84, -70.03], zoom_start=7)
        folium.Marker([-15.84, -70.03], tooltip="Puno", icon=folium.Icon(color="orange")).add_to(mapa)
        st_folium(mapa, width=700, height=450)